# MkDocs configuration file
site_name: Ansible Workshop
copyright: Copyright &copy; Computacenter 2023
extra:
  social:
    - icon: fontawesome/brands/docker
      link: https://github.com/TimGrt/ansible-windows-workshop/blob/main/Dockerfile
      name: Container Definition
extra_css:
  - assets/stylesheets/tables.css
  - assets/stylesheets/extra.css
edit_uri: ""
theme:
  name: material
  custom_dir: docs/assets/overrides
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/ansible-logo-black.png
  language: de
  favicon: assets/images/ansible-logo-black.png
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
  palette:
    - scheme: computacenter
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
plugins:
  - search:
      lang: en
      separator: '[\s]'
  - awesome-pages
  - autolinks
  - print-site:
      add_cover_page: true
      add_print_site_banner: true
      cover_page_template: "docs/assets/pdf/cover-page.tpl"
      enabled: !ENV [ENABLED_PRINT_SITE, True]
      path_to_pdf: "docs/assets/ansible-best-practices.pdf"
      print_page_title: ""
      print_site_banner_template: "docs/assets/pdf/print-banner.tpl"
extra_javascript:
  - assets/extra/refresh-on-toggle-dark-light.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - assets/extra/tablesort.js
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
repo_url: https://github.com/TimGrt/ansible-windows-workshop
repo_name: timgrt/ansible-windows-workshop
# Navigation definition
nav:
  - "Workshop Overview": 
      - index.md
      - preparation.md
  - "Exercises":
    - windows-automation/windows-adhoc.md
    - windows-automation/windows-playbook.md
    - windows-automation/windows-project.md
    - windows-automation/windows-advanced-playbooks.md
    #- windows-automation/windows-roles.md
    - windows-automation/windows-patch.md
